---
:development: &defaults
  :adapter: mysql
  :database: en
  :username: root
  :password:
  :host: localhost
  :encoding: utf8

:test:
  :adapter: sqlite3
  :database: ":memory:"
  :encoding: utf8

:production:
  <<: *defaults
  :database: encounter_production

:rake:
  <<: *defaults