---
:development: &defaults
  :adapter: sqlite3
  :database: db/development.sqlite
  :encoding: utf8

:test:
  :adapter: sqlite3
  :database: ":memory:"
  :encoding: utf8

:production:
  :url: <%= ENV['DATABASE_URL'] %>

:rake:
  <<: *defaults
